package views;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import jogo.Controle;
import javax.swing.ImageIcon;

/**
 * Classe destinada a mostrar as dicas das palavras e mudando-as conforme for
 * acertando
 *
 * @version V3.0
 * @author gabriel
 */
public class SegundoFrame extends javax.swing.JFrame {

    Controle c = new Controle();
    String letrasUtilizadas = "";
    String letrasUsadasJuntas = "";
    String palavraAcerto = "";
    String palavraChute = "";

    /**
     * Creates new form SegundoFrame
     */
    public SegundoFrame() {
        initComponents();

        txtPalavra.setText(c.resetPalavra(c.palavra));
        txtDica.setText(c.dica);
        this.setResizable(false);
        this.setTitle("Jogo da Forca");
        this.setLocationRelativeTo(null);
        btnEnviar.setBackground(Color.blue);

    }

    public void setImg(int num) {

        switch (num) {

            case 0:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/000.jpg")));
                break;
            case 1:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001.jpg")));
                break;
            case 2:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002.jpg")));
                break;
            case 3:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003.jpg")));
                break;
            case 4:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/004.jpg")));
                break;
            case 5:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005.jpg")));
                JOptionPane.showMessageDialog(null, "Última tentativa");
                break;
            case 6:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006.jpg")));
                JOptionPane.showMessageDialog(null, "Perdeu!\nA palavra era: " + c.palavra);
                this.dispose();
                Principal p = new Principal();
                p.setVisible(true);
                break;
        }

    }

    public void certificaAcerto(String palavra, String palavraRevelada) {

        if (palavraRevelada.equals(palavra)) {
            JOptionPane.showMessageDialog(null, "Acertou!");
            this.dispose();
            Principal p = new Principal();
            p.setVisible(true);
        }

    }

    public void verificaLetra(String letra, String letras) {

        if (letra.length() > 1) {
            palavraChute = c.verificaChute(letra, c.palavra);

            txtPalavra.setText(palavraChute);

            certificaAcerto(c.palavra, palavraChute);

            letrasUtilizadas += " " + txtLetra.getText() + ", ";

            txtLetrasUtilizadas.setText(letrasUtilizadas);
        }

        if (letra.length() <= 1) {
            boolean igual = false;

            for (int i = 0; i < letras.length(); i++) {

                if (letra.charAt(0) == letras.charAt(i)) {
                    igual = true;
                }

            }

            if (igual == true) {
                JOptionPane.showMessageDialog(null, "Esta letra já foi inserida\nTente outra letra!");
            } else if (igual == false) {
                txtPalavra.setText(c.setPalavra(c.palavra, txtLetra.getText().toUpperCase()));

                letrasUtilizadas += " " + txtLetra.getText() + ", ";

                txtLetrasUtilizadas.setText(letrasUtilizadas);

                certificaAcerto(c.palavra, palavraAcerto);
            }
        }

    }

    @Override
    public void setResizable(boolean bln) {
        super.setResizable(bln); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setTitle(String string) {
        super.setTitle(string); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setLocationRelativeTo(Component cmpnt) {
        super.setLocationRelativeTo(cmpnt); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mudaImg1 = new views.mudaImg();
        btnEnviar = new javax.swing.JButton();
        txtLetra = new javax.swing.JTextField();
        txtLetrasUtilizadas = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        txtPalavra = new javax.swing.JLabel();
        txtDica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mudaImg1.setImg(new ImageIcon("src/img/imgJogoForcaPrincipal.jpg"));
        mudaImg1.setPreferredSize(new java.awt.Dimension(415, 655));

        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtLetra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLetraKeyPressed(evt);
            }
        });

        txtLetrasUtilizadas.setText("Letras utilizadas");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/000.jpg"))); // NOI18N

        txtPalavra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPalavra.setText("Palavra");

        txtDica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDica.setText("Dica:");

        javax.swing.GroupLayout mudaImg1Layout = new javax.swing.GroupLayout(mudaImg1);
        mudaImg1.setLayout(mudaImg1Layout);
        mudaImg1Layout.setHorizontalGroup(
            mudaImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mudaImg1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(txtLetrasUtilizadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mudaImg1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(mudaImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDica)
                    .addComponent(txtPalavra))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudaImg1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(mudaImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudaImg1Layout.createSequentialGroup()
                        .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudaImg1Layout.createSequentialGroup()
                        .addComponent(img)
                        .addGap(44, 44, 44))))
        );
        mudaImg1Layout.setVerticalGroup(
            mudaImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mudaImg1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtDica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPalavra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mudaImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLetra))
                .addGap(3, 3, 3)
                .addComponent(txtLetrasUtilizadas))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mudaImg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mudaImg1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        palavraAcerto = c.setPalavraAcerto(c.palavra, txtLetra.getText().toUpperCase());

        verificaLetra(txtLetra.getText().toUpperCase(), letrasUsadasJuntas.toUpperCase());

        letrasUsadasJuntas += txtLetra.getText().charAt(0);

        txtLetra.setText("");

        setImg(c.vida);

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtLetraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLetraKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            palavraAcerto = c.setPalavraAcerto(c.palavra, txtLetra.getText().toUpperCase());

            verificaLetra(txtLetra.getText().toUpperCase(), letrasUsadasJuntas.toUpperCase());

            letrasUsadasJuntas += txtLetra.getText().charAt(0);

            txtLetra.setText("");

            setImg(c.vida);

        }

    }//GEN-LAST:event_txtLetraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel img;
    private views.mudaImg mudaImg1;
    private javax.swing.JLabel txtDica;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JLabel txtLetrasUtilizadas;
    private javax.swing.JLabel txtPalavra;
    // End of variables declaration//GEN-END:variables
}
